env:
    DEVICE: viva
    ROMREPO: https://github.com/LineageOS/android.git -b lineage-20.0 --git-lfs
    LOCALMANIFEST: https://github.com/EF-StRM/local_manifests.git
    MAKEFILENAME: lineage-20-viva
    VARIENT: userdebug
    EXTRACMD:
    TARGET: brunch lineage_viva-userdebug
    F: ci:ci #Your Gdrive Folder Path which u have set in rclone
    E: ENCRYPTED[7fd6a1a2996b87cf9c241e03d5fcd275b30396787b1b31ba2f062c716b52f8bae8a9f8b44e5f2a3bcc879ba76a61486f] #Encrypted id which u obtained from cirrusci after encrypting your rclone values
    LINK: #Enter ccache link if u already have for any rom, if u dont have one, collecct firstt

# DONT MODIFY FROM HERE #
task:
  name: "AOSP"
  timeout_in: 120m
  container:
      image: shazuxdd/ubuntu:latest
      cpu: 8
      memory: 32G
  Setup_script:
      - ./scripts/setup.sh || source scripts/setup.sh
  Sync_script:
      - ./scripts/sync.sh || source scripts/sync.sh
  Build_script:
      - ./scripts/build.sh || source scripts/build.sh
  Upload_script:
      - ./scripts/upload.sh || source scripts/upload.sh
