env:
    DEVICE: viva
    ROMREPO: https://github.com/LineageOS/android.git -b lineage-18.1 --git-lfs
    LOCALMANIFEST: https://github.com/EF-StRM/local_manifests.git
    MAKEFILENAME: lineage_viva
    VARIENT: userdebug
    EXTRACMD:
    TARGET: brunch
    LINK: #Enter ccache link if u already have for any rom, if u dont have one, collecct first

# DONT MODIFY FROM HERE #
task:
  name: "AOSP"
  timeout_in: 120m
  container:
      image: shazuxdd/ubuntu:latest
      cpu: 8
      memory: 32G
  Setup_script:
      - ./scripts/setup.sh || source scripts/setup.sh
  Sync_script:
      - ./scripts/sync.sh || source scripts/sync.sh
  Build_script:
      - ./scripts/build.sh || source scripts/build.sh
  Upload_script:
      - ./scripts/upload.sh || source scripts/upload.sh
