name: Trigger CirrusCI

on:
  workflow_dispatch:

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
    - name: Check Out
      uses: actions/checkout@v3
    - name: Display Run Parameters
      run: |
        rm trigger.txt
        echo "#!/bin/bash" >> trigger.txt
        echo "export RANDOM=${RANDOM}" >> trigger.txt
        echo  "::endgroup::"
        cat trigger.txt

    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ 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 }}
        author_email: 'dias.dammahum@gmail.com'
        author_name: 'said'
        message: 'BUILD TRIGGERED'
